version: "3.7"
services:
  db:
    container_name: user-postgre
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mrgerst,2
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data

  redis:
    container_name: redis
    image: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  app:
    image: app
    build: .
    depends_on:
      - db
    ports:
      - "5005:5005"
    environment:
      DB_HOST: db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Mrgerst,2
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres

volumes:
  postgres:
  redis: